### ISSUE TITLE
Argument input to MV_ID3 @doppler010

### ISSUE THREAD

**Issue by SND96** [SND96/Random-Forests-Matlab#13]
The numbers in the examples and the outcomes have to be input **separately** (matlab doesn't support arrays with different data types) . Modify decision tree.m for this.

**Comment by PNR-1** [comment]
Why don't we input the entire thing as a string, then use methods to convert to Int?

**Comment by SND96** [comment]
We'll still need to split it. It won't be able to hold two different data types once we convert it.

**Comment by SND96** [comment]
Or we'll have to convert the outcomes to numbers and then input them
